### ISSUE TITLE
Executing on an existing machine is extremely dangerous

### ISSUE THREAD

**Issue by buddyp450** [stephenway/sysconfig#4]
It's obvious to me now that this is meant for brand spanking new machines but for the love of all that is holy and good, please please PLEASE add a revert option to restore all of the ~/.config's back to what they were before if needed.

**Comment by stephenway** [comment]
If your playing around with dotfiles, then  you might want to use [homesick](https://github.com/technicalpickles/homesick) to try them out first before sticking with one. I'm sure it wouldn't be hard to add a backup task that just renames all the current matching symlinks. I can add it in, but it might be a while, maybe you could submit a PR?

**Comment by buddyp450** [comment]
Thanks for the recommendation, no time to submit a PR right now (lol, I'm behind from borking my dotfiles) but I'll definitely check out homesick.
